version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver_container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"

  your_service_name:
    image: sha256:a8e361e0e175d0bcd65b024ed8f961b0d8472dc00a16b14b6979709d5c341c3d
    environment:
      - CONNECTION_STRING=Server=sqlserver_container;Database=Company;User Id=sa;Password=yourStrong(!)Password;
    ports:
      - "8080:80"
    depends_on:
      - sqlserver